name: build

on:
  push:
    branches: ["*"]
  workflow_dispatch:
    inputs:
      version:
        description: "Version to build, e.g. 0.1.0"
        type: string
        required: false

env:
  PKG_NAME: "vault-servicenow-credential-resolver"

jobs:
  get-product-version:
    runs-on: ubuntu-latest
    outputs:
      product-version: ${{ steps.get-product-version.outputs.product-version }}
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: get product version
        id: get-product-version
        run: |
          VERSION="${{ github.event.inputs.version || '0.0.0-dev' }}"
          echo "Using version ${VERSION}"
          echo "::set-output name=product-version::${VERSION}"
  generate-metadata-file:
    needs: get-product-version
    runs-on: ubuntu-latest
    outputs:
      filepath: ${{ steps.generate-metadata-file.outputs.filepath }}
    steps:
      - name: 'Checkout directory'
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Generate metadata file
        id: generate-metadata-file
        uses: hashicorp/actions-generate-metadata@v1
        with:
          version: ${{ needs.get-product-version.outputs.product-version }}
          product: ${{ env.PKG_NAME }}

      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: metadata.json
          path: ${{ steps.generate-metadata-file.outputs.filepath }}

  build:
    needs: get-product-version
    runs-on: ubuntu-latest

    name: Build Jar

    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Build
        id: build-binary
        env:
          VERSION: ${{ needs.get-product-version.outputs.product-version }}
        run: |
          mkdir out
          ./gradlew jar
          ZIP_FILE="out/${{ env.PKG_NAME }}_${{ needs.get-product-version.outputs.product-version }}_all_all.zip"
          zip -r -j "${ZIP_FILE}" build/libs/ LICENSE
          echo "path=${ZIP_FILE}" >> $GITHUB_OUTPUT
          echo "name=$(basename ${ZIP_FILE})" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: ${{ steps.build-binary.outputs.name }}
          path: ${{ steps.build-binary.outputs.path }}
